FROM resin/%%RESIN_MACHINE_NAME%%-debian

MAINTAINER Gergely Imreh <gergely@resin.io>

WORKDIR /usr/src/app

# Enable systemd
ENV INITSYSTEM on

# Create an exctra mount point
RUN echo "tmpfs  /cache  tmpfs  rw,size=200M,nosuid,nodev,noexec  0 0" >> /etc/fstab

# copy current directory into /app
COPY . ./

# run python script when container lands on device
CMD ["bash", "start.sh"]