FROM resin/%%RESIN_MACHINE_NAME%%-debian

WORKDIR /usr/src/app

# Enable systemd
ENV INITSYSTEM on

RUN echo "tmpfs   /data/cache    tmpfs  rw,size=200M,nr_inodes=5k,noexec,nodev,nosuid,uid=648,gid=648,mode=1700   0  0" >> /etc/fstab

RUN mkdir -p /data/cache

# copy current directory into /app
COPY . ./

# run python script when container lands on device
CMD ["bash", "start.sh"]