FROM resin/%%RESIN_MACHINE_NAME%%-debian

WORKDIR /usr/src/app

# Enable systemd
ENV INITSYSTEM on

RUN echo "tmpfs   /cache    tmpfs  rw,size=200M  0  0" >> /etc/fstab

# copy current directory into /app
COPY . ./

# run python script when container lands on device
CMD ["bash", "start.sh"]